<template>
  <pre class="text-[4.8px]">
                                                                                                                                          dddddddd
MMMMMMMM               MMMMMMMM                hhhhhhh                                                                                    d::::::d     YYYYYYY       YYYYYYY                                                                        ffffffffffffffff       EEEEEEEEEEEEEEEEEEEEEE  iiii
M:::::::M             M:::::::M                h:::::h                                                                                    d::::::d     Y:::::Y       Y:::::Y                                                                       f::::::::::::::::f      E::::::::::::::::::::E i::::i
M::::::::M           M::::::::M                h:::::h                                                                                    d::::::d     Y:::::Y       Y:::::Y                                                                      f::::::::::::::::::f     E::::::::::::::::::::E  iiii
M:::::::::M         M:::::::::M                h:::::h                                                                                    d:::::d      Y::::::Y     Y::::::Y                                                                      f::::::fffffff:::::f     EE::::::EEEEEEEEE::::E
M::::::::::M       M::::::::::M   ooooooooooo   h::::h hhhhh         aaaaaaaaaaaaa      mmmmmmm    mmmmmmm     aaaaaaaaaaaaa      ddddddddd:::::d      YYY:::::Y   Y:::::YYYooooooooooo   uuuuuu    uuuuuu      ssssssssss       eeeeeeeeeeee     f:::::f       ffffff       E:::::E       EEEEEEiiiiiii     ssssssssss       ssssssssss     aaaaaaaaaaaaa
M:::::::::::M     M:::::::::::M oo:::::::::::oo h::::hh:::::hhh      a::::::::::::a   mm:::::::m  m:::::::mm   a::::::::::::a   dd::::::::::::::d         Y:::::Y Y:::::Y oo:::::::::::oo u::::u    u::::u    ss::::::::::s    ee::::::::::::ee   f:::::f                    E:::::E             i:::::i   ss::::::::::s    ss::::::::::s    a::::::::::::a
M:::::::M::::M   M::::M:::::::Mo:::::::::::::::oh::::::::::::::hh    aaaaaaaaa:::::a m::::::::::mm::::::::::m  aaaaaaaaa:::::a d::::::::::::::::d          Y:::::Y:::::Y o:::::::::::::::ou::::u    u::::u  ss:::::::::::::s  e::::::eeeee:::::eef:::::::ffffff              E::::::EEEEEEEEEE    i::::i ss:::::::::::::s ss:::::::::::::s   aaaaaaaaa:::::a
M::::::M M::::M M::::M M::::::Mo:::::ooooo:::::oh:::::::hhh::::::h            a::::a m::::::::::::::::::::::m           a::::ad:::::::ddddd:::::d           Y:::::::::Y  o:::::ooooo:::::ou::::u    u::::u  s::::::ssss:::::se::::::e     e:::::ef::::::::::::f              E:::::::::::::::E    i::::i s::::::ssss:::::ss::::::ssss:::::s           a::::a
M::::::M  M::::M::::M  M::::::Mo::::o     o::::oh::::::h   h::::::h    aaaaaaa:::::a m:::::mmm::::::mmm:::::m    aaaaaaa:::::ad::::::d    d:::::d            Y:::::::Y   o::::o     o::::ou::::u    u::::u   s:::::s  ssssss e:::::::eeeee::::::ef::::::::::::f              E:::::::::::::::E    i::::i  s:::::s  ssssss  s:::::s  ssssss     aaaaaaa:::::a
M::::::M   M:::::::M   M::::::Mo::::o     o::::oh:::::h     h:::::h  aa::::::::::::a m::::m   m::::m   m::::m  aa::::::::::::ad:::::d     d:::::d             Y:::::Y    o::::o     o::::ou::::u    u::::u     s::::::s      e:::::::::::::::::e f:::::::ffffff              E::::::EEEEEEEEEE    i::::i    s::::::s         s::::::s        aa::::::::::::a
M::::::M    M:::::M    M::::::Mo::::o     o::::oh:::::h     h:::::h a::::aaaa::::::a m::::m   m::::m   m::::m a::::aaaa::::::ad:::::d     d:::::d             Y:::::Y    o::::o     o::::ou::::u    u::::u        s::::::s   e::::::eeeeeeeeeee   f:::::f                    E:::::E              i::::i       s::::::s         s::::::s    a::::aaaa::::::a
M::::::M     MMMMM     M::::::Mo::::o     o::::oh:::::h     h:::::ha::::a    a:::::a m::::m   m::::m   m::::ma::::a    a:::::ad:::::d     d:::::d             Y:::::Y    o::::o     o::::ou:::::uuuu:::::u  ssssss   s:::::s e:::::::e            f:::::f                    E:::::E       EEEEEE i::::i ssssss   s:::::s ssssss   s:::::s a::::a    a:::::a
M::::::M               M::::::Mo:::::ooooo:::::oh:::::h     h:::::ha::::a    a:::::a m::::m   m::::m   m::::ma::::a    a:::::ad::::::ddddd::::::dd            Y:::::Y    o:::::ooooo:::::ou:::::::::::::::uus:::::ssss::::::se::::::::e          f:::::::f                 EE::::::EEEEEEEE:::::Ei::::::is:::::ssss::::::ss:::::ssss::::::sa::::a    a:::::a
M::::::M               M::::::Mo:::::::::::::::oh:::::h     h:::::ha:::::aaaa::::::a m::::m   m::::m   m::::ma:::::aaaa::::::a d:::::::::::::::::d         YYYY:::::YYYY o:::::::::::::::o u:::::::::::::::us::::::::::::::s  e::::::::eeeeeeee  f:::::::f                 E::::::::::::::::::::Ei::::::is::::::::::::::s s::::::::::::::s a:::::aaaa::::::a
M::::::M               M::::::M oo:::::::::::oo h:::::h     h:::::h a::::::::::aa:::am::::m   m::::m   m::::m a::::::::::aa:::a d:::::::::ddd::::d         Y:::::::::::Y  oo:::::::::::oo   uu::::::::uu:::u s:::::::::::ss    ee:::::::::::::e  f:::::::f                 E::::::::::::::::::::Ei::::::i s:::::::::::ss   s:::::::::::ss   a::::::::::aa:::a
MMMMMMMM               MMMMMMMM   ooooooooooo   hhhhhhh     hhhhhhh  aaaaaaaaaa  aaaammmmmm   mmmmmm   mmmmmm  aaaaaaaaaa  aaaa  ddddddddd   ddddd         YYYYYYYYYYYYY    ooooooooooo       uuuuuuuu  uuuu  sssssssssss        eeeeeeeeeeeeee  fffffffff                 EEEEEEEEEEEEEEEEEEEEEEiiiiiiii  sssssssssss      sssssssssss      aaaaaaaaaa  aaaa


  </pre>
</template>
